### ISSUE TITLE
packaged native source zip doesn't preserve execute permission

### ISSUE THREAD

**Issue by mingfai** [fusesource/hawtjni#15]
I followed leveldbjni to setup a maven project structure as follows:

```
  test-project
  test-project/test
  test-project/test-osx
```

test-project/test contains the native source and when I use "mvn install", it successfully package and install the native source to a test-VERSION-native-src.zip. However, the zip contain does not preserve the original file mode, and the build script at test-osx under target/native-build-extracted/ expect certain files be executable. 

I notice maven-hawtjni-plugin uses a very old version of Plexus Archiver, that doesn't seem to have too much options to set file mode. So i upgraded the dependency in the maven-hawtjni-plugin project as follows:

```
<dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-archiver</artifactId>
      <version>2.4.4</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-container-default</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-component-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-io</artifactId>
      <version>2.0.10</version>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-container-default</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-component-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

with the new version, I modified PackageSourceMojo.java to try different options for the Archiver but I have no idea how to set it to preserve the original file mode. From an old issue, it seems to support setting the mode by default:
http://jira.codehaus.org/browse/PLXCOMP-94
but in practice, it just do not set the file mode correctly in OSX

Anyway, as a test, I hardcoded the mode, and then the zipped files have execute permission to run the script in make.

```
 Archiver archiver = archiverManager.getArchiver( "zip" );
            archiver.setFileMode(Archiver.DEFAULT_DIR_MODE);//hardcoded
            archiver.setDestFile( packageFile);
```

Sorry I have no solution. Otherwise I would have sent a pull request. Let me know if you have any idea I have test it. thx

**Comment by gnodet** [comment]
It seems to work for me.  The `configure` script has the correct `-rwxr--r--` permissions for example.
