### ISSUE TITLE
Missing tag for 1.16

### ISSUE THREAD

**Issue by msimacek** [fusesource/hawtjni#46]
1.16 is available on Maven Central, but not tagged here on GitHub

**Comment by wltjr** [comment]
A tag is needed for [Jansi 1.17.1 which needs changes to Library.java](https://github.com/fusesource/jansi/blob/jansi-project-1.17.1/jansi/src/main/java/org/fusesource/jansi/AnsiMain.java#L61) in hawtjni-runtime 1.16. I had to grab an update to [Library.java](https://github.com/Obsidian-StudiosInc/os-xtoo/blob/master/dev-java/hawtjni-runtime/files/Library_java.diff) and added that to 1.15. Though I could do a snapshot for 1.16. Rather see an actual tag if you all do not mind. Thank you!

**Comment by ebourg** [comment]
The tag is also needed to update the hawtjni package in Debian.

git tag hawtjni-project-16 fa1fd5df

**Comment by gnodet** [comment]
Tag has been uploaded, sorry for the delay.

**Comment by ebourg** [comment]
Thank you!
