### ISSUE TITLE
shared_ptr support is not present 

### ISSUE THREAD

**Issue by ossdev07** [fusesource/hawtjni#51]
shared_ptr support is missing in hawt jni so we made changes . verified it with librocksdbjni and raised the pull request 

https://github.com/fusesource/hawtjni/pull/50

**Comment by gnodet** [comment]
Can you add an example usage of `shared_ptr` to the [hawtjni-example](https://github.com/fusesource/hawtjni/tree/master/hawtjni-example) ? I fear it's somewhat broken.

**Comment by gnodet** [comment]
I've reverted the merge of #51 until a working example is provided.

**Comment by gnodet** [comment]
And btw, I'd like to release `hawtjni` this week, let me know if you plan to provide something soon.

**Comment by ossdev07** [comment]
Reference to the newly generated PR #57 , provided the support of shared pointer with an example.
Test Report for the reference :
[hawtjni_aarch64_testReport.txt](https://github.com/fusesource/hawtjni/files/3140794/hawtjni_aarch64_testReport.txt)

**Comment by rhenwood-arm** [comment]
Hi @ossdev07 and @gnodet 

As an Arm user, I have an interest in seeing this work landed.

@ossdev07 : I've looked briefly through the log file you posted. It is over 5K lines long. It apparently looks like a build task. Please can you highlight the example usage of 'shared_ptr' as it is no obvious to me.

**Comment by rhenwood-arm** [comment]
Ah, I see that this ticket has been closed, I will move my comments to #57 ...
