### ISSUE TITLE
Please add more infos on the project license(s)

### ISSUE THREAD

**Issue by fbricon** [fusesource/hawtjni#52]
Hi, while trying to get hawtjni-runtime usage approved by the Eclipse Foundation, the IP team got stuck with: 

>  While the project license appears to be Apache-2.0, the headers reference EPL-1.0.

Since I found both the license.txt and pom.xml reference both licenses, I imagine the project is dual licensed. It'd be nice to make it explicit in the project readme

**Comment by chirino** [comment]
It's a mix of both.  Use the license that applies is the one the header specifies.  The EPL licensed files originated from the eclipse project.  New file were created for this project were created with the ASL 2.0 license.
